### create role
POST http://localhost:3000/role/create_role
Content-Type: application/json

{
    "role_name":"Admin"
}

### create role
POST http://localhost:3000/role/create_role
Content-Type: application/json

{
    "role_name":"User"
}

### Get all roles
GET http://localhost:3000/role/getall_roles